### ISSUE TITLE
alfred cli utility stopped working

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/go-alfred#7]
Not sure why but now the alfred CLI tool does nothing for me. `alfred info` shows nothing. `alfred build` which worked before stopped working.

It all happened after I ran `go install github.com/jason0x43/go-alfred/alfred` thinking it would update my command because my old version did not have `alfred release` command.

**Comment by jason0x43** [comment]
Here's where go's lack of versioning is a bit of a pain, since it's going to be tricky to tell where the problem was introduced.

Does running just `alfred` show the help output?

**Comment by nikivdev** [comment]
Running just `alfred` returns this : 

```Bash
panic: error reading plist file: open info.plist: no such file or directory

goroutine 1 [running]:
github.com/jason0x43/go-alfred.LoadPlist(0x1372223, 0xa, 0x0)
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/plist.go:18 +0xf0
github.com/jason0x43/go-alfred.init.1()
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/main.go:140 +0x1e4
github.com/jason0x43/go-alfred.init()
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/workflow.go:683 +0xfa
main.init()
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/alfred/main.go:415 +0x76
```

**Comment by jason0x43** [comment]
Ah. The alfred command assumes it's being run in a workflow project, which is assumed to have the structure:

```
<project>
    <source files>
    ...
    workflow/
        info.plist
        <workflow files>
```

It can be run from the project root, or from the `workflow` directory within the project.

When the command starts up, the first thing it does is open the workflow's info.plist file. If there isn't one (because, say, you're running the command outside of a workflow project), it panics. (Not the most user-friendly behavior.)

**Comment by nikivdev** [comment]
Yeah you are right. Bad example by me.

When I run it from the workflow project `alfred` shows nothing when ran.

Here is my workflow dir : 

```
~/go/src/github.com/nikitavoloboev/alfred-web-searches master*
❯ tree
.
├── LICENSE
├── main.go
├── media
│   ├── alfred.png
│   └── fuzzy.png
├── readme.md
└── workflow
    ├── alfred-web-searches
    ├── icon.png
    ├── icons
    │   ├── doc.png
    │   ├── forums.png
    │   ├── github.png
    │   ├── reddit.png
    │   ├── stack.png
    │   ├── translate.png
    │   └── update.png
    ├── info.plist
    └── websites.csv

3 directories, 17 files
```

It worked perfectly well before. I used `alfred link` to link the workflow and then `alfred build` was building it perfectly. But after update none of the commands work.

**Comment by jason0x43** [comment]
I pushed up a new version with some debug logging. Install that, then run alfred using

```
$ alfred_debug=1 alfred
```

You can also try any of the sub-commands link info or build. With the `alfred_debug` environment variable set, you should see some debug output like

```
[alfred] 2017/09/14 09:30:06 Alfred version:
[alfred] 2017/09/14 09:30:06 prefs dir: ~/Library/Mobile Documents/com~apple~CloudDocs/Alfred
[alfred] 2017/09/14 09:30:06 workflows path: ~/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows
usage: alfred <command>

command may be one of:
    build      build the workflow executable (-a to rebuild libs)
    clean      clean built files
    info       display information about the current workflow
    link       activate this workflow
    pack       create a distributable package
    unlink     deactivate this workflow
```

**Comment by nikivdev** [comment]
Okay I installed it. This is what I get running `alfred` with debug env var : 

```Bash
alfred_debug=1 alfred
[alfred] 2017/09/14 15:36:31 Alfred version:
[alfred] 2017/09/14 15:36:31 Could not determine Alfred version
```

I get the same for `alfred build` too

**Comment by nikivdev** [comment]
I even tried to bootstrap new workflow for development with `alfred link` and still get the same log : 

```Bash
~/go/src/github.com/nikitavoloboev/alfred-testing
❯ tree
.
├── main.go
└── workflow
    ├── icon.png
    └── info.plist

1 directory, 3 files

~/go/src/github.com/nikitavoloboev/alfred-testing
❯ alfred_debug=1 alfred link
[alfred] 2017/09/14 15:40:25 Alfred version:
[alfred] 2017/09/14 15:40:25 Could not determine Alfred version
```

**Comment by nikivdev** [comment]
Perhaps something broke since Alfred released a new version?

**Comment by jason0x43** [comment]
What's happening there is that the command is trying to figure out what version of Alfred is installed on your system. That bit of init code is used in workflows that use go-alfred as well as the `alfred` cli command. Depending on how the code is run (by Alfred itself in the case of a workflow, or from the command line when running `alfred`), it will either use an environment variable or will look through your `/Applications` folder for an Alfred app.

That bit of code hasn't been updated for more than a year, so if that's the problem you were probably using a very old version of `alfred` (or the Alfred app may have been relocated on your system).

Is Alfred installed on your system, or is it in a non-standard location (like ~/Applications)?

**Comment by nikivdev** [comment]
I am using [this library](https://github.com/deanishe/awgo) to develop my workflows. I just use your cli to link and build the workflows and hopefully ease releasing them too once I figure it out.

Alfred is installed on my system in the default place I guess. 

`/Applications/Alfred 3.app`

Not really sure what is wrong. And yeah I probably was using the old version but that old version worked perfectly before. Not sure why when I go get the command again, everything broke.

**Comment by jason0x43** [comment]
Interesting, I didn't know deanishe had started working with Go. It is quite nice for workflows. :)

Ah well, at least we're making progress. I pushed a new version that includes some log statements showing what it's looking at regarding the Alfred app. Give that a try.

**Comment by nikivdev** [comment]
Just to make sure I understand correctly. This command updates my CLI command?

`go install github.com/jason0x43/go-alfred/alfred`

**Comment by jason0x43** [comment]
Try `go get -u github.com/jason0x43/go-alfred/alfred`, which should update and re-install the package. I don't believe `go install` will download or update packages.

**Comment by nikivdev** [comment]
Okay. I get this now : 

```Bash
❯ alfred_debug=1 alfred
[alfred] 2017/09/14 17:31:04 Alfred version:
[alfred] 2017/09/14 17:31:04 Looking for app in /Applications
[alfred] 2017/09/14 17:31:04 Ignoring (A Document Being Saved By Keyboard Maestro Engine)
[alfred] 2017/09/14 17:31:04 Ignoring .DS_Store
[alfred] 2017/09/14 17:31:04 Ignoring .localized
[alfred] 2017/09/14 17:31:04 Ignoring 1Password.app
[alfred] 2017/09/14 17:31:04 Ignoring 2Do.app
[alfred] 2017/09/14 17:31:04 Ignoring 5.3
[alfred] 2017/09/14 17:31:04 Using Alfred 3.app
[alfred] 2017/09/14 17:31:04 Using Alfred Metadata Tool.app
[alfred] 2017/09/14 17:31:04 Ignoring Bartender 2.app
[alfred] 2017/09/14 17:31:04 Found app at Alfred Metadata Tool.app
[alfred] 2017/09/14 17:31:04 Could not determine Alfred version
```

**Comment by jason0x43** [comment]
Ah, that'd be it. My logic there just needs to be a bit smarter (or I should just assume you're using Alfred 3).

**Comment by jason0x43** [comment]
I pushed an update that's a bit more discriminating about the app file name it's looking for. Try that.

**Comment by nikivdev** [comment]
Sweet. This works. 🎊 

This tool really makes developing workflows fun. Thank you for sharing it. 

I've been thinking of perhaps trying to add [Goreleaser](https://github.com/goreleaser/goreleaser) somehow to my releasing of workflows. 

What is your process like for releasing workflows and updates to them? I am curious. 🙂

**Comment by jason0x43** [comment]
Workflows have versions like `1.5.0-pre` locally (the version on my machine is the next one that will be released). When a new release is ready, I run `alfred release`, which increments and updates the version (e.g., to 1.5.0), commits and tags the release, creates an .alfredworkflow file, then updates the version to the next pre-version (e.g., 1.5.1-pre) and commits that to the repo. Then I push the repo updates (including the release tag) to GitHub, write some release notes and attach the alfredworkflow file, and also update the package on packal (life would be much simpler if packal could look at GitHub for release info).

**Comment by nikivdev** [comment]
Thank you for sharing.

Is it possible to add an option to the cli to pack the .zip to ~/Desktop instead of workflow directory?

I would really appreciate it. 💛

**Comment by nikivdev** [comment]
Also [Godoc](https://godoc.org/github.com/jason0x43/go-alfred/alfred) broke with your new update. 😞

**Comment by jason0x43** [comment]
> Is it possible to add an option to the cli to pack the .zip to ~/Desktop instead of workflow directory?

Sure

> Also Godoc broke with your new update. 😞

Oops, I mistakenly reformatted a doc comment.

**Comment by nikivdev** [comment]
Thank you @jason0x43 

Also, I [wrote an article today](https://medium.com/@NikitaVoloboev/writing-alfred-workflows-in-go-2a44f62dc432) on how to start developing alfred workflows using Go using AwGo and alfred CLI.

Perhaps you will find it interesting. Although it's aimed to be introductory to people new to Go and Alfred. 🙂

**Comment by jason0x43** [comment]
Nice article!

The `release` and `pack` commands can now take an output option, `-o some_directory`.

**Comment by jason0x43** [comment]
Closing this since it's fixed.
